### ISSUE TITLE
Logo and icons are to be updated with new logo

### ISSUE THREAD

**Issue by s-katte** [astrosonic/community-website#17]

**Comment by AlacritousCreature** [comment]
I would like to work on this issue. But the community website's Repo isn't in this repository. Where can it be done?

**Comment by gridhead** [comment]
Hi @AlacritousCreature, thank you for your interest in this issue. I am assigning this to you. Do make sure to register at our official Hacktoberfest event at https://organize.mlh.io/participants/events/4659-hack-astrosonic to stay connected with all fellow contributors of this repository. 

Coming to your question, I am not sure if I understand it. Could you please elaborate?

**Comment by AlacritousCreature** [comment]
Hi @t0xic0der thanku for assigning! I have registered to be able to contribute to this project in proper way. The AstroCoder Community website's( which I saw on AstroCode organizations github page) repository is not on this community-website repository. I mean the source code of that website is not on this repository, so from where can I fork and work on this issue? 

Sorry, if I misunderstood anything :), or am not aware of where the source code lies. Please guide me where the contribution to be made.

**Comment by gridhead** [comment]
We are a different community, called AstroSonic and not AstroCode.

The website is written using MkDocs and it conveniently uses markdown for all layout and structuring. 

Further reading
- https://www.markdownguide.org/
- https://www.mkdocs.org/#getting-started
- https://squidfunk.github.io/mkdocs-material/getting-started/

Stay in collaboration with other contributors via this ticket and of course, the event registration. Happy hacking! :smile:

**Comment by AlacritousCreature** [comment]
Extremely sorry for miss spelling it, I meant the same AstroSonic github account. Now I got that it is using Mkdocs for constructing it. I will explore it asap and am on it. Thank you for guiding through, and if I get stuck please help through it.  :sweat_smile:

**Comment by gridhead** [comment]
Sure. We have this ticket where you can comment on whenever you need help and of course, we have our official Hacktoberfest event.

**Comment by AlacritousCreature** [comment]
Hi @t0xic0der and @s-katte ! I read Mkdocs for making the required changes. But in this repo there isn't a image file or a .svg of new logo of AstroSonic, to add it by making changes in mkdocs.yml file. Please tell how to seek it...or should I take Screenshot of it and compress it?

**Comment by s-katte** [comment]
Here are the links to the logos that we have been having a hard time to choose from.

- [logo 1](https://mega.nz/file/1MozVYJL#cKcmVpPugdWSmH_dxC9gwqjgC4bCps5iqRypGXwUv1c)
- [logo 2](https://mega.nz/file/oFgRDIZR#vw2jXCcS6igAtHZD5aqipANcI56bigdDDJtlDLJWXhg
)
Select anyone that you think would look the best and make it the logo of the site.

**Comment by AlacritousCreature** [comment]
Okay :smiley:

**Comment by gridhead** [comment]
Closed #17 via #23 

Thank you for your contributions, @AlacritousCreature. :smile:
