### ISSUE TITLE
Update list of AstroSonic Core Team

### ISSUE THREAD

**Issue by s-katte** [astrosonic/community-website#18]

**Comment by gridhead** [comment]
Wanna pick this up, @s-katte?

**Comment by s-katte** [comment]
Yes, please assign it to me.

**Comment by gridhead** [comment]
There you go. Happy hacking! :smile:

**Comment by gridhead** [comment]
Any updates, @s-katte?

**Comment by s-katte** [comment]
This issue is already resolved [here](https://github.com/astrosonic/community-website/pull/19)

**Comment by shivangswain** [comment]
Still has a few issues, I'd say. @s-katte, your tagline's formatting is a bit wonky. Also, those added to the core list are supposed to be removed from the regular community member's list, I suppose.

**Comment by s-katte** [comment]
> Still has a few issues, I'd say. @s-katte, your tagline's formatting is a bit wonky. Also, those added to the core list are supposed to be removed from the regular community member's list, I suppose.

sure, will look into it
