### ISSUE TITLE
Inform about hacktoberbest event in the dedicated events page

### ISSUE THREAD

**Issue by s-katte** [astrosonic/community-website#20]

**Comment by gridhead** [comment]
Allow me to pick this one up, @s-katte. :smile:

**Comment by s-katte** [comment]
There you go @t0xic0der !

**Comment by shristi54** [comment]
would be glad if you'll assign me to solve an issue. 'cause i think i can do this!

**Comment by s-katte** [comment]
Hey @shristi54, thank you for showing your interest to contribute, this issue is already assigned to @t0xic0der. You can explore other issues as there are plenty of them. Head over [here](https://initiative.astrosonic.tech/) and pick one.

Happy hacking!
